name: VPSDeploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Deploy static files
        run: |
          cd app && cp -R -v . /var/www/js.x.ks.ua/
